import Head from "next/head";
import { NextPage } from "next";
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from "next";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

// data type
interface Data {
  Hello: string;
  data: string;
}

const Home: NextPage<Data> = (Hello) => {
  console.log(Hello);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to FastAPI {Hello.Hello}</h1>
      </main>
    </>
  );
};

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async (context) => {
  // Fetch data from external API
  const res = await fetch(`https://python-fastapi.vercel.app/`);
  const data = await res.json();

  // Pass data to the page via props
  return {
    props: {
      Hello: data.Hello,
    },
  };
};

export default Home;
